
= Welcome to MCQ Kokkos

*Quiz on the concept of Hierarchical Parallelism*

++++
<script>
function checkAnswer(questionName, rightAnswer, resultId) {
    let answer = document.querySelector(`input[name="${questionName}"]:checked`)?.value;
    let result = document.getElementById(resultId);
    if (answer === rightAnswer) {
        result.innerHTML = "Correct!";
    } else {
        result.innerHTML = "Wrong answer, try again.";
    }
}
</script>

<div id="question1">
    <p>1. What is a thread team in Kokkos?</p>
    <input type="radio" name="q1" value="a"> A group of CPUs<br>
    <input type="radio" name="q1" value="b"> A collection of threads that can synchronize and share scratch memory<br>
    <input type="radio" name="q1" value="c"> A set of GPUs<br>
    <input type="radio" name="q1" value="d"> A type of View Kokkos<br>
    <button onclick="checkAnswer('q1', 'b', 'result1')">Submit</button>
    <p id="result1"></p>
</div>

<div id="question2">
    <p>2. How many levels of nested parallelism does Kokkos allow?</p>
    <input type="radio" name="q2" value="a"> 2<br>
    <input type="radio" name="q2" value="b"> 3<br>
    <input type="radio" name="q2" value="c"> 4<br>
    <input type="radio" name="q2" value="d"> Unlimited<br>
    <button onclick="checkAnswer('q2', 'b', 'result2')">Submit</button>
    <p id="result2"></p>
</div>

<div id="question3">
    <p>3. What execution policy is used for hierarchical parallelism?</p>
    <input type="radio" name="q3" value="a"> RangePolicy<br>
    <input type="radio" name="q3" value="b"> TeamPolicy<br>
    <input type="radio" name="q3" value="c"> HierarchyPolicy<br>
    <input type="radio" name="q3" value="d"> NestedPolicy<br>
    <button onclick="checkAnswer('q3', 'b', 'result3')">Submit</button>
    <p id="result3"></p>
</div>

<div id="question4">
    <p>4. What is the finest level of parallelism in Kokkos?</p>
    <input type="radio" name="q4" value="a"> League<br>
    <input type="radio" name="q4" value="b"> Team<br>
    <input type="radio" name="q4" value="c"> Thread<br>
    <input type="radio" name="q4" value="d"> Vector<br>
    <button onclick="checkAnswer('q4', 'd', 'result4')">Submit</button>
    <p id="result4"></p>
</div>

<div id="question5">
    <p>5. What method is used to synchronize threads within a team?</p>
    <input type="radio" name="q5" value="a"> <code>team_sync()</code><br>
    <input type="radio" name="q5" value="b"> <code>team_barrier()</code><br>
    <input type="radio" name="q5" value="c"> <code>team_wait()</code><br>
    <input type="radio" name="q5" value="d"> <code>team_fence()</code><br>
    <button onclick="checkAnswer('q5', 'b', 'result5')">Submit</button>
    <p id="result5"></p>
</div>

<div id="question6">
    <p>6. What type of memory is shared between threads in the same team?</p>
    <input type="radio" name="q6" value="a"> Global memory<br>
    <input type="radio" name="q6" value="b"> Shared memory<br>
    <input type="radio" name="q6" value="c"> Scratch memory<br>
    <input type="radio" name="q6" value="d"> Team memory<br>
    <button onclick="checkAnswer('q6', 'c', 'result6')">Submit</button>
    <p id="result6"></p>
</div>

<div id="question7">
    <p>7. What policy is used for thread-level parallelism in a team?</p>
    <input type="radio" name="q7" value="a"> TeamThreadRange<br>
    <input type="radio" name="q7" value="b"> ThreadTeamRange<br>
    <input type="radio" name="q7" value="c"> TeamParallelRange<br>
    <input type="radio" name="q7" value="d"> ParallelTeamRange<br>
    <button onclick="checkAnswer('q7', 'a', 'result7')">Submit</button>
    <p id="result7"></p>
</div>

<div id="question8">
    <p>8. What is the main advantage of hierarchical parallelism in Kokkos?</p>
    <input type="radio" name="q8" value="a"> Simplification of the code<br>
    <input type="radio" name="q8" value="b"> Reduction of memory consumption<br>
    <input type="radio" name="q8" value="c"> Better exploitation of different levels of hardware parallelism<br>
    <input type="radio" name="q8" value="d"> Increased accuracy of calculations<br>
    <button onclick="checkAnswer('q8', 'c', 'result8')">Submit</button>
    <p id="result8"></p>
</div>
++++